Repository OctobearHub/octobear.org, pull requests merged in 2022-10, with the labels that each got.

#1 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#3 feat/#2: Add community facedetection project
  src/assets/data/comunity_repositories.json
Labels: hacktoberfest-accepted

#6 added three resources for front-end developers
  src/assets/data/resources.json
Labels: hacktoberfest-accepted

#9 Added 2 events
  public/images/ICSDMD.jpg
  public/images/ndc_london.jpg
  src/assets/data/programs.json
Labels: hacktoberfest-accepted

#15 Modified resources.json file and added json object with title Add tai…
  package-lock.json
  src/assets/data/resources.json
Labels: hacktoberfest-accepted

#14 Added additional resources for frontend developers
  src/assets/data/resources.json
Labels: hacktoberfest-accepted

#13 Added Outreachy 2023 to programs.json
  src/assets/data/programs.json
Labels: hacktoberfest-accepted

#21 Work branch
  src/assets/data/resources.json
Labels: hacktoberfest-accepted

#27 feat: display tags of the resource in its card and show all tags available
  src/components/tag/index.jsx
  src/pages/resources.jsx
Labels: hacktoberfest-accepted

#29 Add events
  src/assets/data/programs.json
Labels: hacktoberfest-accepted

#31 feat: add icons resources
  src/assets/data/resources.json
Labels: hacktoberfest-accepted

#19 Added new resource
  src/assets/data/resources.json
Labels: hacktoberfest-accepted

#20 Added MLH Fellowship
  src/assets/data/programs.json
Labels: hacktoberfest-accepted

#38 Added an adding images tutorial readme file. Solves issue #33
  Attaching_Images_To_Data.md
  src/components/footer/index.jsx
Labels: hacktoberfest-accepted

#37 feat: new program
  src/assets/data/programs.json
Labels: hacktoberfest-accepted

#39 Filter by tags
  src/assets/data/resources.json
  src/components/tag/index.jsx
  src/pages/resources.jsx
Labels: hacktoberfest-accepted

#43 refs #42
  .gitignore
  src/components/tag/index.jsx
Labels: hacktoberfest-accepted

#47 Create SECURITY.md
  SECURITY.md
Labels: hacktoberfest-accepted

#51 add github skills to resources
  src/assets/data/resources.json
Labels: hacktoberfest-accepted

#59 Add an event
  src/assets/data/programs.json
Labels: hacktoberfest-accepted, hacktoberfest

#62 Addig new resources
  src/assets/data/resources.json
Labels: change requested
